### ISSUE TITLE
WildTools still not supporting GenCubes

### ISSUE THREAD

**Issue by ItzFabb-uwu** [BG-Software-LLC/WildTools#101] opened 2022-04-06 14:16 UTC
### Minecraft's Version

1.18.2

### Plugin's Version

WildTools-2.12.0-b56

### Describe the bug

Still when i break the cubes with 3by3 2by2 pickaxe it can breaks the outlines of the cubes

### To Reproduce

Mine the cubes with a 3by3 Pickaxe

### Additional Information

https://youtu.be/sV9V-7clfkk

**Comment by ItzFabb-uwu** [comment] 2022-04-06 14:16
And no there is no issue at the console its just the wildtools you can break outlines/the border of the cubes + when i mines it the "items" won't get dropped inside the cubes

**Comment by OmerBenGera** [comment] 2022-04-06 14:34
Do you have GenCubes's plugin name (the exact one from /pl) in the `other-plugins` list in your config file?

**Comment by ItzFabb-uwu** [comment] 2022-04-06 14:36
yessir

**Comment by ItzFabb-uwu** [comment] 2022-04-06 14:37
####################################################
##                                                ##
##            WildTools Configuration             ##
##               Developed by Ome_R               ##
##                                                ##
####################################################

# Choose which prices plugin to check for prices (ShopGUIPlus, Essentials, CMI, newtShop, QuantumShop, EconomyShopGUI, WildTools).
prices-plugin: 'ShopGUIPlus'

# Path to the logs file.
# You may disable it by setting the path to be empty.
logs-file: 'logs.txt'

# A list of prices. Use "TYPE" and "TYPE:DATA" formats.
prices-list:
- 'STONE:5' #Each stone will cost $5
- 'LOG:0:5' #Only oak logs will cost $5

# Here you can configure which plugins will be called, etc.
# Optimizing the lists will result better performance!
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
    - SuperiorSkyblock2
  # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins:
    - GenCubes

**Comment by ItzFabb-uwu** [comment] 2022-04-06 14:42
Me and Developer of Gencubes
Deadsilence4

https://media.discordapp.net/attachments/957858669637296128/959660274934218813/unknown.png

https://media.discordapp.net/attachments/957858669637296128/959660297201782794/unknown.png

https://media.discordapp.net/attachments/957858669637296128/959660749096103976/unknown.png

**Comment by ItzFabb-uwu** [comment] 2022-04-06 14:45
!
![Uploading unknown.png…]()
![Uploading unknown.png…]()
![Uploading unknown.png…]()

Few of the sneak peak for the wildtools & gencubes

**Comment by ItzFabb-uwu** [comment] 2022-04-07 04:03
so any news?

**Comment by OmerBenGera** [comment] 2022-04-07 04:38
> so any news?

Patient dude.
Havent looked into it yet... its been less than a day...

Once I have more information I will let you know

**Comment by DeadSilenceIV** [comment] 2022-04-10 02:34
Hello Omer, looking into WildTools API i didn't found a way of preventing some blocks from being destroyed while using the Trench pickaxe, am i missing something?. I really appreciate you help thanks <3.

**Comment by DeadSilenceIV** [comment] 2022-04-10 02:40
i would also like to know if there's a way of preventing the blocks drops when using the Cuboid wand, maybe adding some kind of method to the CuboidWandUseEvent class might be helpful as i would be able to handle some blocks drops on my side.

**Comment by OmerBenGera** [comment] 2022-04-10 04:48
> Hello Omer, looking into WildTools API i didn't find a way of preventing some blocks from being destroyed while using the Trench pickaxe, am i missing something?. I really appreciate your help thanks ❤️.

Cancel BlockBreakEvent

**Comment by OmerBenGera** [comment] 2022-04-10 04:49
> i would also like to know if there's a way of preventing the blocks drops when using the Cuboid wand, maybe adding some kind of method to the CuboidWandUseEvent class might be helpful as i would be able to handle some blocks drops on my side.

People can configure the blocks to be dropped in the config file

**Comment by DeadSilenceIV** [comment] 2022-04-10 05:22
> > Hello Omer, looking into WildTools API i didn't find a way of preventing some blocks from being destroyed while using the Trench pickaxe, am i missing something?. I really appreciate your help thanks heart.
> 
> Cancel BlockBreakEvent

Yeah, the thing is that i don't want to cancel the whole action, i just want to exclude some blocks from being broken when the Cuboid wand is used.

**Comment by DeadSilenceIV** [comment] 2022-04-10 05:23
> > i would also like to know if there's a way of preventing the blocks drops when using the Cuboid wand, maybe adding some kind of method to the CuboidWandUseEvent class might be helpful as i would be able to handle some blocks drops on my side.
> 
> People can configure the blocks to be dropped in the config file

The reason of why i want to prevent the block drops it's because they're supposed to be added into the Cube's inventory and not being thrown on floor.

**Comment by DeadSilenceIV** [comment] 2022-04-10 05:27
> 

In this case i would like to exclude the cube borders from being broken.

https://youtu.be/sV9V-7clfkk?t=25

**Comment by OmerBenGera** [comment] 2022-04-10 15:58
> > > Hello Omer, looking into WildTools API i didn't find a way of preventing some blocks from being destroyed while using the Trench pickaxe, am i missing something?. I really appreciate your help thanks heart.
> > 
> > 
> > Cancel BlockBreakEvent
> 
> Yeah, the thing is that i don't want to cancel the whole action, i just want to exclude some blocks from being broken when the Cuboid wand is used.

Its similar to vanilla - cancelling BlockBreakEvent to prevent people from breaking blocks... how else do you prevent them from breaking the blocks?

**Comment by OmerBenGera** [comment] 2022-04-10 15:59
If you already cancel the event, then @ItzFabb-uwu should add the plugin to the claiming-plugins list so the plugin respects the cancelation of the event.

**Comment by OmerBenGera** [comment] 2022-04-16 08:16
Any news regarding this?

**Comment by ItzFabb-uwu** [comment] 2022-04-16 08:22
No fixes what soever.. im waiting till gencubes update

**Comment by OmerBenGera** [comment] 2022-04-16 08:28
> No fixes what soever.. im waiting till gencubes update

The issue is that players are able to break blocks that they cannot break while using regular pickaxes, right?

**Comment by ItzFabb-uwu** [comment] 2022-04-16 09:03
Yeah

**Comment by OmerBenGera** [comment] 2022-04-16 09:25
> Yeah

Even after adding it to the `claiming-plugins` list in your config (Not `other-plugins` as I said before)?
I know I told you to this already, just making sure

**Comment by ItzFabb-uwu** [comment] 2022-04-16 10:36
I have added that if you are not sure look at the top of this issue lol ive put 
- GenCubes
- gencubes
- GENCUBES
- Gencubes #still wont work

**Comment by OmerBenGera** [comment] 2022-04-16 11:15
> I have added that
> 
> * GenCubes
> * gencubes
> * GENCUBES
> * Gencubes #still wont work

Send me your entire config.

@DeadSilenceIV , may I get access to your plugin so I can test it out on localhost?

**Comment by DeadSilenceIV** [comment] 2022-04-16 11:37
Sure, let me add you in spigot

**Comment by OmerBenGera** [comment] 2022-04-16 11:51
> Sure, let me add you on spigot

Thanks.
My spigot is Ome_R

**Comment by OmerBenGera** [comment] 2022-04-16 12:04
I tested it and by adding `GenCubes` to the `claiming-plugins` list in the config, players cannot break the mine.
```yaml
# Here you can configure which plugins will be called, etc.
# Optimizing the lists will result better performance!
events-manipulations:
  # A list of all the plugins that handle claims here on your server.
  # If one of the plugins here cancel the events, then WT will know that the player doesn't have access.
  claiming-plugins:
  - GenCubes
  # A list of all the other plugins that needs to know about breaking of blocks.
  # You can add your custom shops plugins, spawners plugin and more.
  # WildTools will not care if events are cancelled from this list. Therefore, if WildTools needs to know
  # if the events are cancelled from a plugin, add it to the 'claiming-plugins' section.
  other-plugins: []
```

**Comment by OmerBenGera** [comment] 2022-04-16 12:16
@DeadSilenceIV If you want to override drops for WildTools (so blocks are not dropped inside mines), you can do that by registering your own `DropsProvider`. You can find javadocs here: https://bg-software.com/wildtools/api/ 

For registering your own DropsProvider, use `WildToolsAPI.getWildTools().getProviders#addDropsProvider`
You should check if the block that was broken is inside a GenCube, and if it is return an empty list, otherwise return null (to tell the plugin to handle drops on its own in the rest of the world)

**Comment by ItzFabb-uwu** [comment] 2022-04-17 02:08
I dont know how it did get fixed the only issue is that the item dannot get stored inside the cubes
https://pastebin.com/pNSQWke2

**Comment by OmerBenGera** [comment] 2022-04-17 04:51
> I dont know how it did get fixed the only issue is that the item dannot get stored inside the cubes https://pastebin.com/pNSQWke2

Items were stored fine for me. They were stored as well as dropped, which I explained to @DeadSilenceIV how to fix it.

**Comment by OmerBenGera** [comment] 2022-04-23 07:38
I am closing this as it's fixed from WT's side.

**Closed by OmerBenGera** 2022-04-23 07:38 UTC
Labels: ❌ Unconfirmed
