### ISSUE TITLE
Trench pickaxe is not collecting blocks, its only destroying

### ISSUE THREAD

**Issue by DiktatorAladeen** [BG-Software-LLC/WildTools#181] opened 2023-12-27 22:47 UTC
### Minecraft's Version

![image](https://github.com/BG-Software-LLC/WildTools/assets/34982264/278eba79-76cc-4448-928c-104eea9be1df)

### Plugin's Version

![image](https://github.com/BG-Software-LLC/WildTools/assets/34982264/4b6020b6-e377-405c-9674-4605a5497aec)

### Describe the bug

Hi,

Trench pickaxes are not collecting blocks while digging. Its only destroying and sometimes he pick up some ores or blocks.

### To Reproduce

////

### Additional Information

This is config for trench pickaxes:
tools:
  trench_pickaxe:
    tool-mode: CUBOID
    break-level: 5
    auto-collect: true
    uses: 10000
    type: DIAMOND_PICKAXE
    name: '&f --{ &9&lTrench Pickaxe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Ovaj Pickaxe radi tunel 5x5.'
    - '&f'
    - '&9&l Blokirani blokovi:'
    - '&f - &7Spawner'
    - '&f - &7Obsidian'
    - '&f - &7Bedrock'
    - '&f'
    - '&9&l Uses:'
    - '&f   {}'
    - '&f'
    - '&7 Itemi sami ulaze u vas inventory.'
    - '&8&m---------------------------------------'
    enchants:
    - DIG_SPEED:6
    blacklisted-blocks:
    - BEDROCK
    - MOB_SPAWNER
    - SPAWNER
    - CHEST
    - ENDER_CHEST
    - BARRELL
    - SHULKER_BOX
    - LIME_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - BLACK_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - PINK_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - RED_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - NETHER_PORTAL
    - OBSERVER
    whitelisted-drops:
    - COAL
    - IRON_ORE
    - LAPIS_LAZULI
    - GOLD_ORE
    - REDSTONE
    - DIAMOND
    - EMERALD
    - QUARTZ
    - ANCIENT_DEBRIS
    - NETHER_GOLD_ORE
    - GOLD_NUGGET
    - RAW_GOLD
    - RAW_IRON
    - RAW_COPPER
    - COPPER_ORE
    - STONE
    - COBBLED_DEEPSLATE
    - TUFF
    - ANDESITE
    - GRANITE
    - DIORITE
    - OBSIDIAN
  all_pickaxe:
    tool-mode: CUBOID
    break-level: 3
    auto-collect: true
    uses: 15000
    type: NETHERITE_PICKAXE
    name: '&f --{ &9&l3x3 Pickaxe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Ovaj Pickaxe radi tunel 3x3.'
    - '&f'
    - '&9&l Blokirani blokovi:'
    - '&f - &7Spawner'
    - '&f - &7Obsidian'
    - '&f - &7Bedrock'
    - '&f'
    - '&9&l Uses:'
    - '&f   {}'
    - '&f'
    - '&7 Itemi sami ulaze u vas inventory.'
    - '&8&m---------------------------------------'
    enchants:
    - DIG_SPEED:6
    blacklisted-blocks:
    - MOB_SPAWNER
    - OBSIDIAN
    - BEDROCK
    whitelisted-drops:
    - COAL
    - RAW_COPPER
    - COPPER_INGOT
    - LAPIS_LAZULI
    - RAW_IRON
    - DIORITE
    - ANDESITE
    - DEEPSLATE
    - GRANITE
    - RAW_GOLD
    - TUFF
    - DIRT
    - SANDSTONE
    - ANCIENT_DEBRIS
    - STONE
    - COBBLESTONE
    - IRON_ORE
    - GOLD_ORE
    - REDSTONE
    - INK_SACK:4
    - DIAMOND
    - EMERALD
    - QUARTZ
  all_pickaxe2:
    tool-mode: CUBOID
    break-level: 7
    auto-collect: true
    uses: 10000
    type: NETHERITE_PICKAXE
    name: '&f --{ &5&l7x7 Pickaxe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Ovaj Pickaxe radi tunel 7x7.'
    - '&f'
    - '&5&l Blokirani blokovi:'
    - '&f - &7Spawner'
    - '&f - &7Obsidian'
    - '&f - &7Bedrock'
    - '&f'
    - '&5&l Uses:'
    - '&f   {}'
    - '&f'
    - '&7 Itemi sami ulaze u vas inventory.'
    - '&8&m---------------------------------------'
    enchants:
    - DIG_SPEED:6
    blacklisted-blocks:
    - MOB_SPAWNER
    - OBSIDIAN
    - BEDROCK
    whitelisted-drops:
    - COAL
    - RAW_COPPER
    - COPPER_INGOT
    - LAPIS_LAZULI
    - RAW_IRON
    - DIORITE
    - ANDESITE
    - DEEPSLATE
    - GRANITE
    - RAW_GOLD
    - TUFF
    - DIRT
    - SANDSTONE
    - ANCIENT_DEBRIS
    - STONE
    - IRON_ORE
    - GOLD_ORE
    - REDSTONE
    - INK_SACK:4
    - DIAMOND
    - EMERALD
    - QUARTZ

**Comment by OmerBenGera** [comment] 2024-01-12 16:27
It works fine for me, and I suspect one of the followings is the cause:
- Your are in creative mode
- You have whitelisted drops configured, but the blocks you break don't drop any of the whitelisted drops
- Another plugin interfaces with the plugin

Make sure neither of the above can cause the issue

**Comment by OmerBenGera** [comment] 2024-02-16 13:53
I am closing this as it seems to be a faulty configuration file
If the issue continues let me know

**Closed by OmerBenGera** 2024-02-16 13:53 UTC
Labels: 🔧 Potential fix
