### ISSUE TITLE
Wildtools tool used A message appears in the console.

### ISSUE THREAD

**Issue by Wisherss** [BG-Software-LLC/WildTools#125] opened 2022-08-05 02:55 UTC
### Minecraft's Version

paper 1.19.1 #109

### Plugin's Version

wildtools #74

### Describe the bug

Every time the tools are used, a message appears in the console.
![Screenshot 2022-08-04 153626](https://user-images.githubusercontent.com/107991332/182991750-2fff8203-2b4c-412d-ba05-2c6b4523c6b7.png)

### To Reproduce

When starting to use Tools to break blocks

**Comment by OmerBenGera** [comment] 2022-08-05 07:55
Mind sending me the error via pastebin?
Also, send the error you get from b74, as this error doesn't match the lines of b74

**Comment by OmerBenGera** [comment] 2022-08-06 13:44
The issue is fixed with latest builds

**Closed by OmerBenGera** 2022-08-06 13:44 UTC
Labels: 📝 Missing information
