### ISSUE TITLE
Height limit problem with the builder tools

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildTools#138] opened 2023-02-23 13:33 UTC
### Minecraft's Version

Minecraft version paper 1.8.8-445

### Plugin's Version

Latest version

### Describe the bug

When we want to use the builder wand and we arrive at the maximum layer an error is displayed in the console and the blocks are not posed any more but they are invisible (we remain blocked in the block). This bug is annoying because I want to create a pillar that goes up 100 blocks.

### To Reproduce

Create the builder wand with a length of 100 and try to climb to the maximum layer.

### Additional Information

Is it possible to add an option to check that we do not want to try to exceed the limit of the map and add a message that explains it to us.

**Comment by OmerBenGera** [comment] 2023-02-24 11:59
Upload the error to pastebin and send it here

**Comment by iJuju68** [comment] 2023-02-24 12:17
Here is the error : https://pastebin.com/gCztY4KF

I also have a problem with the trench pickaxe when I mine, only coal ores are given the others are removed, I use the default plugin configuration. What should I do to solve the problem?

**Comment by OmerBenGera** [comment] 2023-02-25 07:43
Update the plugin to latest dev build, let me know if it works

**Comment by iJuju68** [comment] 2023-02-25 11:47
I just installed the latest dev build but I still have the same error and I can't get the ores

**Comment by iJuju68** [comment] 2023-03-05 14:47
Were you able to look up my problem?

**Comment by OmerBenGera** [comment] 2023-03-17 14:48
@iJuju68 Sorry for the long waiting time, the issue is fixed in latest dev build

**Closed by OmerBenGera** 2023-03-17 14:48 UTC
Labels: 📝 Missing information
