### ISSUE TITLE
Error when mining stacked blocks from superiorskyblock2

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/WildTools#109] opened 2022-05-24 14:22 UTC
### Minecraft's Version

1.16 airplane

### Plugin's Version

Dev #60 

### Describe the bug

If you break a blacklisted block, which is stacked by superiorskyblock2 with a 3x3 pickaxe, it shows this error on console:
https://paste.md-5.net/isusohapuj.md

### To Reproduce

Stack a block using superiorskyblock2
break it

**Comment by OmerBenGera** [comment] 2022-05-24 17:16
Duplicate of #108

**Closed by OmerBenGera** 2022-05-24 17:16 UTC
Labels: Pending
