### ISSUE TITLE
ShopGuiPlus hook not working

### ISSUE THREAD

**Issue by Florens11** [BG-Software-LLC/WildTools#85] opened 2022-01-03 21:52 UTC
### Minecraft's Version

[22:50:41 INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

### Plugin's Version

2.11.3

### Describe the bug

If you put shopguiplus in the price provider it doesnt work.

### To Reproduce

Put shopguiplus in the config of wildtools.

### Additional Information

I'm using an older version for now while this bug is being patched. It works fine on there with the same config.

**Comment by OmerBenGera** [comment] 2022-01-04 08:06
Duplicate of #82

**Closed by OmerBenGera** 2022-01-04 08:06 UTC
Labels: Pending
